;             
CREATE USER IF NOT EXISTS SA SALT 'a04b44f1297fa837' HASH '09a79417fba75e104c629cc8027f5db88b9894338f97f6e3294450e7f9c3f580' ADMIN;           
CREATE SCHEMA IF NOT EXISTS PA AUTHORIZATION SA;              
DROP TABLE IF EXISTS PA.AUTHORISATION CASCADE;
DROP TABLE IF EXISTS PA.SALT CASCADE;         
DROP TABLE IF EXISTS PA.PASSWORD CASCADE;     
DROP TABLE IF EXISTS PA.ROLESTATUT CASCADE;   
DROP TABLE IF EXISTS PA.AUTHORISATIONROLE CASCADE;            
DROP TABLE IF EXISTS PA.EQUATION CASCADE;     
DROP TABLE IF EXISTS PA.USERS CASCADE;        
DROP TABLE IF EXISTS PA.USERROLE CASCADE;     
DROP TABLE IF EXISTS PA.COMMENTARY CASCADE;   
DROP TABLE IF EXISTS PA.ELEMENT CASCADE;      
DROP TABLE IF EXISTS PA.EQUATIONELEMENT CASCADE;              
DROP TABLE IF EXISTS PA.RULE CASCADE;         
DROP TABLE IF EXISTS PA.RULEELEMENT CASCADE;  
DROP TABLE IF EXISTS PA.ELMTOPERATOR CASCADE; 
DROP TABLE IF EXISTS PA.ELMTVARIABLE CASCADE; 
DROP TABLE IF EXISTS PA.EQUATIONRULES CASCADE;
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_79190BEE_F7FD_4B2D_866A_8C769D2BFAE0 START WITH 12 BELONGS_TO_TABLE;       
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_FF60A56E_EB6F_4525_BF2F_52BACABD95F1 START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_E270FB88_04DF_430D_9A0B_88D39B52B562 START WITH 13 BELONGS_TO_TABLE;       
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_2B0DE45E_2570_43B4_AF72_993AD1E1D4EF START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_226539DE_E4D0_4C41_8A57_9135B81289B1 START WITH 13 BELONGS_TO_TABLE;       
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_789E34B0_5B49_4DD0_AFF3_D7F5A5CCC6ED START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_DF00DC8E_AD8F_4421_88FF_5BD08BCDA31B START WITH 13 BELONGS_TO_TABLE;       
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_66F5576B_4B0D_460B_9D16_0AE812A186F6 START WITH 13 BELONGS_TO_TABLE;       
CREATE CACHED TABLE PA.AUTHORISATION(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_79190BEE_F7FD_4B2D_866A_8C769D2BFAE0) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_79190BEE_F7FD_4B2D_866A_8C769D2BFAE0,
    LABEL TEXT,
    VAL BOOL
);              
ALTER TABLE PA.AUTHORISATION ADD CONSTRAINT PA.CONSTRAINT_5 PRIMARY KEY(ID);  
-- 11 +/- SELECT COUNT(*) FROM PA.AUTHORISATION;              
INSERT INTO PA.AUTHORISATION(ID, LABEL, VAL) VALUES
(1, 'test', TRUE),
(2, 'testtest', TRUE),
(3, 'testtest', TRUE),
(4, 'testtest', TRUE),
(5, 'testtest', TRUE),
(6, 'testtest', TRUE),
(7, 'testtest', TRUE),
(8, 'testtest', TRUE),
(9, 'testtest', TRUE),
(10, 'testtest', TRUE),
(11, 'testtest', TRUE);     
CREATE CACHED TABLE PA.SALT(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_66F5576B_4B0D_460B_9D16_0AE812A186F6) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_66F5576B_4B0D_460B_9D16_0AE812A186F6,
    VAL TEXT
);        
ALTER TABLE PA.SALT ADD CONSTRAINT PA.CONSTRAINT_2 PRIMARY KEY(ID);           
-- 12 +/- SELECT COUNT(*) FROM PA.SALT;       
INSERT INTO PA.SALT(ID, VAL) VALUES
(1, 'salt'),
(2, 'salt'),
(3, 'salt'),
(4, 'salt'),
(5, 'salt'),
(6, 'salt'),
(7, 'salt'),
(8, 'salt'),
(9, 'salt'),
(10, 'salt'),
(11, 'salt'),
(12, 'salt');
CREATE CACHED TABLE PA.PASSWORD(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_E270FB88_04DF_430D_9A0B_88D39B52B562) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_E270FB88_04DF_430D_9A0B_88D39B52B562,
    VAL TEXT,
    ID_SALT INT
);  
ALTER TABLE PA.PASSWORD ADD CONSTRAINT PA.CONSTRAINT_7 PRIMARY KEY(ID);       
-- 12 +/- SELECT COUNT(*) FROM PA.PASSWORD;   
INSERT INTO PA.PASSWORD(ID, VAL, ID_SALT) VALUES
(1, '1234', 1),
(2, '1234', 1),
(3, '1234', 1),
(4, '1234', 1),
(5, '1234', 1),
(6, '1234', 1),
(7, '1234', 1),
(8, '1234', 1),
(9, '1234', 1),
(10, '1234', 1),
(11, '1234', 1),
(12, '1234', 1);               
CREATE CACHED TABLE PA.ROLESTATUT(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_2B0DE45E_2570_43B4_AF72_993AD1E1D4EF) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_2B0DE45E_2570_43B4_AF72_993AD1E1D4EF,
    LABEL TEXT
);
ALTER TABLE PA.ROLESTATUT ADD CONSTRAINT PA.CONSTRAINT_A PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PA.ROLESTATUT;  
CREATE CACHED TABLE PA.AUTHORISATIONROLE(
    ID INT,
    AUT_ID INT
);    
-- 0 +/- SELECT COUNT(*) FROM PA.AUTHORISATIONROLE;           
CREATE CACHED TABLE PA.EQUATION(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_DF00DC8E_AD8F_4421_88FF_5BD08BCDA31B) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_DF00DC8E_AD8F_4421_88FF_5BD08BCDA31B,
    LABEL TEXT,
    DESCRIPTION TEXT,
    ISVALID BOOL,
    VALIDATEDBY INT,
    VALIDATIONDATE DATE
);        
ALTER TABLE PA.EQUATION ADD CONSTRAINT PA.CONSTRAINT_51 PRIMARY KEY(ID);      
-- 12 +/- SELECT COUNT(*) FROM PA.EQUATION;   
INSERT INTO PA.EQUATION(ID, LABEL, DESCRIPTION, ISVALID, VALIDATEDBY, VALIDATIONDATE) VALUES
(1, NULL, NULL, NULL, NULL, NULL),
(2, NULL, NULL, NULL, NULL, NULL),
(3, NULL, NULL, NULL, NULL, NULL),
(4, NULL, NULL, NULL, NULL, NULL),
(5, NULL, NULL, NULL, NULL, NULL),
(6, NULL, NULL, NULL, NULL, NULL),
(7, NULL, NULL, NULL, NULL, NULL),
(8, NULL, NULL, NULL, NULL, NULL),
(9, NULL, NULL, NULL, NULL, NULL),
(10, NULL, NULL, NULL, NULL, NULL),
(11, NULL, NULL, NULL, NULL, NULL),
(12, NULL, NULL, NULL, NULL, NULL);               
CREATE CACHED TABLE PA.USERS(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_226539DE_E4D0_4C41_8A57_9135B81289B1) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_226539DE_E4D0_4C41_8A57_9135B81289B1,
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    USERNAME TEXT,
    CREATEDATE DATE,
    UPDATEDATE DATE,
    ISACTIVE BOOL,
    ISDELETED BOOL,
    ID_EQUATION INT,
    ID_PASSWORD INT
);        
ALTER TABLE PA.USERS ADD CONSTRAINT PA.CONSTRAINT_4 PRIMARY KEY(ID);          
-- 12 +/- SELECT COUNT(*) FROM PA.USERS;      
INSERT INTO PA.USERS(ID, FIRSTNAME, LASTNAME, USERNAME, CREATEDATE, UPDATEDATE, ISACTIVE, ISDELETED, ID_EQUATION, ID_PASSWORD) VALUES
(1, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(2, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(3, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(4, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(5, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(6, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(7, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(8, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(9, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(10, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(11, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1),
(12, 'firstName', 'lastName', 'userName', DATE '2016-05-16', DATE '2016-05-16', TRUE, FALSE, 1, 1);      
CREATE CACHED TABLE PA.USERROLE(
    ID INT,
    ROL_ID INT
);             
-- 0 +/- SELECT COUNT(*) FROM PA.USERROLE;    
CREATE CACHED TABLE PA.COMMENTARY(
    ID INT,
    EQU_ID INT,
    COMMENTARY TEXT,
    COMMENTDATE DATE
);              
-- 0 +/- SELECT COUNT(*) FROM PA.COMMENTARY;  
CREATE CACHED TABLE PA.ELEMENT(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_789E34B0_5B49_4DD0_AFF3_D7F5A5CCC6ED) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_789E34B0_5B49_4DD0_AFF3_D7F5A5CCC6ED,
    LABEL TEXT,
    DESCRIPTION TEXT
);            
ALTER TABLE PA.ELEMENT ADD CONSTRAINT PA.CONSTRAINT_C PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PA.ELEMENT;     
CREATE CACHED TABLE PA.EQUATIONELEMENT(
    ID INT,
    ELE_ID INT
);      
-- 0 +/- SELECT COUNT(*) FROM PA.EQUATIONELEMENT;             
CREATE CACHED TABLE PA.RULE(
    ID INT DEFAULT (NEXT VALUE FOR PA.SYSTEM_SEQUENCE_FF60A56E_EB6F_4525_BF2F_52BACABD95F1) NOT NULL NULL_TO_DEFAULT SEQUENCE PA.SYSTEM_SEQUENCE_FF60A56E_EB6F_4525_BF2F_52BACABD95F1,
    LABEL TEXT
);      
ALTER TABLE PA.RULE ADD CONSTRAINT PA.CONSTRAINT_26 PRIMARY KEY(ID);          
-- 0 +/- SELECT COUNT(*) FROM PA.RULE;        
CREATE CACHED TABLE PA.RULEELEMENT(
    ID INT,
    ELE_ID INT,
    VAL TEXT
);           
-- 0 +/- SELECT COUNT(*) FROM PA.RULEELEMENT; 
CREATE CACHED TABLE PA.ELMTOPERATOR(
    ID INT
);          
-- 0 +/- SELECT COUNT(*) FROM PA.ELMTOPERATOR;
CREATE CACHED TABLE PA.ELMTVARIABLE(
    ID INT,
    VAL TEXT
);           
-- 0 +/- SELECT COUNT(*) FROM PA.ELMTVARIABLE;
CREATE CACHED TABLE PA.EQUATIONRULES(
    ID INT,
    RUL_ID INT
);        
-- 0 +/- SELECT COUNT(*) FROM PA.EQUATIONRULES;               
ALTER TABLE PA.EQUATIONRULES ADD CONSTRAINT PA.CONSTRAINT_5196 FOREIGN KEY(RUL_ID) REFERENCES PA.RULE(ID) NOCHECK;            
ALTER TABLE PA.EQUATIONRULES ADD CONSTRAINT PA.CONSTRAINT_519 FOREIGN KEY(ID) REFERENCES PA.EQUATION(ID) NOCHECK;             
ALTER TABLE PA.EQUATIONELEMENT ADD CONSTRAINT PA.CONSTRAINT_88 FOREIGN KEY(ELE_ID) REFERENCES PA.ELEMENT(ID) NOCHECK;         
ALTER TABLE PA.AUTHORISATIONROLE ADD CONSTRAINT PA.CONSTRAINT_797 FOREIGN KEY(AUT_ID) REFERENCES PA.AUTHORISATION(ID) NOCHECK;
ALTER TABLE PA.EQUATIONELEMENT ADD CONSTRAINT PA.CONSTRAINT_8 FOREIGN KEY(ID) REFERENCES PA.EQUATION(ID) NOCHECK;             
ALTER TABLE PA.RULEELEMENT ADD CONSTRAINT PA.CONSTRAINT_9 FOREIGN KEY(ID) REFERENCES PA.RULE(ID) NOCHECK;     
ALTER TABLE PA.COMMENTARY ADD CONSTRAINT PA.CONSTRAINT_52 FOREIGN KEY(ID) REFERENCES PA.USERS(ID) NOCHECK;    
ALTER TABLE PA.USERROLE ADD CONSTRAINT PA.CONSTRAINT_1 FOREIGN KEY(ID) REFERENCES PA.USERS(ID) NOCHECK;       
ALTER TABLE PA.ELMTVARIABLE ADD CONSTRAINT PA.CONSTRAINT_4B FOREIGN KEY(ID) REFERENCES PA.ELEMENT(ID) NOCHECK;
ALTER TABLE PA.USERS ADD CONSTRAINT PA.CONSTRAINT_4D FOREIGN KEY(ID_EQUATION) REFERENCES PA.EQUATION(ID) NOCHECK;             
ALTER TABLE PA.COMMENTARY ADD CONSTRAINT PA.CONSTRAINT_528 FOREIGN KEY(EQU_ID) REFERENCES PA.EQUATION(ID) NOCHECK;            
ALTER TABLE PA.ELMTOPERATOR ADD CONSTRAINT PA.CONSTRAINT_78 FOREIGN KEY(ID) REFERENCES PA.ELEMENT(ID) NOCHECK;
ALTER TABLE PA.PASSWORD ADD CONSTRAINT PA.CONSTRAINT_77 FOREIGN KEY(ID_SALT) REFERENCES PA.SALT(ID) NOCHECK;  
ALTER TABLE PA.RULEELEMENT ADD CONSTRAINT PA.CONSTRAINT_99 FOREIGN KEY(ELE_ID) REFERENCES PA.ELEMENT(ID) NOCHECK;             
ALTER TABLE PA.AUTHORISATIONROLE ADD CONSTRAINT PA.CONSTRAINT_79 FOREIGN KEY(ID) REFERENCES PA.ROLESTATUT(ID) NOCHECK;        
ALTER TABLE PA.USERS ADD CONSTRAINT PA.CONSTRAINT_4D4 FOREIGN KEY(ID_PASSWORD) REFERENCES PA.PASSWORD(ID) NOCHECK;            
ALTER TABLE PA.USERROLE ADD CONSTRAINT PA.CONSTRAINT_1E FOREIGN KEY(ROL_ID) REFERENCES PA.ROLESTATUT(ID) NOCHECK;             
