;             
CREATE USER IF NOT EXISTS SA SALT '3992c0f051f5321d' HASH '20007e6953be232d53445bfcbeb269d1ede8ceae19bd81957867458f5561725c' ADMIN;           
CREATE SCHEMA IF NOT EXISTS PA AUTHORIZATION SA;              
DROP TABLE IF EXISTS PA.AUTHORISATION CASCADE;
DROP TABLE IF EXISTS PA.PASSWORD CASCADE;     
DROP TABLE IF EXISTS PA.ROLESTATUT CASCADE;   
DROP TABLE IF EXISTS PA.AUTHORISATIONROLE CASCADE;            
DROP TABLE IF EXISTS PA.EQUATION CASCADE;     
DROP TABLE IF EXISTS PA.USERS CASCADE;        
DROP TABLE IF EXISTS PA.USERROLE CASCADE;     
DROP TABLE IF EXISTS PA.COMMENTARY CASCADE;   
DROP TABLE IF EXISTS PA.ELEMENT CASCADE;      
DROP TABLE IF EXISTS PA.EQUATIONELEMENT CASCADE;              
DROP TABLE IF EXISTS PA.RULE CASCADE;         
DROP TABLE IF EXISTS PA.RULEELEMENT CASCADE;  
DROP TABLE IF EXISTS PA.ELMTOPERATOR CASCADE; 
DROP TABLE IF EXISTS PA.ELMTVARIABLE CASCADE; 
DROP TABLE IF EXISTS PA.EQUATIONRULES CASCADE;
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_50178723_BA2C_4EAA_B8E6_1CCE53410FE7 START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_3B4D5BD6_5B88_4320_9E29_B26BD8880FE6 START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_D81A5B53_17B5_4E45_88B4_ECAA7EEE69CF START WITH 5 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_91A0DFE1_9728_455B_B9FA_EC180B7EBE8C START WITH 5 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_C11724AD_71AD_4B66_AE6B_0E776E0629D7 START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_253BFABF_57BB_46B3_9158_265AA58588FD START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_7B069173_9A3D_4F16_8F59_BB04DA7F98BE START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_7A623C8E_1A76_4827_9F87_7FE9D769E02C START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_F1C8148F_137E_4218_9A74_0EC177A258DA START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_1268A331_74E3_4DC1_895D_D017AF107E58 START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_23D414EB_CDEC_42CF_A906_DF038A8E3FBC START WITH 1 BELONGS_TO_TABLE;        
CREATE SEQUENCE PA.SYSTEM_SEQUENCE_DC303CC4_2F45_40DF_8133_F3A87BBC3977 START WITH 1 BELONGS_TO_TABLE;        
CREATE CACHED TABLE PA.AUTHORISATION(
    ID INT NOT NULL,
    LABEL TEXT,
    VAL BOOL
);
ALTER TABLE PA.AUTHORISATION ADD CONSTRAINT PA.CONSTRAINT_5 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PA.AUTHORISATION;               
CREATE CACHED TABLE PA.PASSWORD(
    ID INT NOT NULL,
    VAL TEXT
);      
ALTER TABLE PA.PASSWORD ADD CONSTRAINT PA.CONSTRAINT_7 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PA.PASSWORD;    
CREATE CACHED TABLE PA.ROLESTATUT(
    ID INT NOT NULL,
    LABEL TEXT
);  
ALTER TABLE PA.ROLESTATUT ADD CONSTRAINT PA.CONSTRAINT_A PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PA.ROLESTATUT;  
CREATE CACHED TABLE PA.AUTHORISATIONROLE(
    ID INT NOT NULL,
    AUT_ID INT
);           
-- 0 +/- SELECT COUNT(*) FROM PA.AUTHORISATIONROLE;           
CREATE CACHED TABLE PA.EQUATION(
    ID INT NOT NULL,
    LABEL TEXT,
    DESCRIPTION TEXT,
    ISVALID BOOL,
    VALIDATEDBY INT,
    VALIDATIONDATE DATE,
    CREATEDBY INT
);      
ALTER TABLE PA.EQUATION ADD CONSTRAINT PA.CONSTRAINT_51 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PA.EQUATION;    
CREATE CACHED TABLE PA.USERS(
    ID INT NOT NULL,
    FIRSTNAME VARCHAR(25) NOT NULL,
    LASTNAME VARCHAR(25) NOT NULL,
    USERNAME VARCHAR(25) NOT NULL,
    CREATEDATE DATE,
    UPDATEDATE DATE,
    ISACTIVE BOOL,
    ISDELETED BOOL,
    ID_PASSWORD INT,
    EMAIL TEXT
);               
ALTER TABLE PA.USERS ADD CONSTRAINT PA.CONSTRAINT_4 PRIMARY KEY(ID, USERNAME);
-- 0 +/- SELECT COUNT(*) FROM PA.USERS;       
CREATE CACHED TABLE PA.USERROLE(
    ID INT NOT NULL,
    ROL_ID INT
);    
-- 0 +/- SELECT COUNT(*) FROM PA.USERROLE;    
CREATE CACHED TABLE PA.COMMENTARY(
    ID INT NOT NULL,
    EQU_ID INT,
    COMMENTARY TEXT,
    COMMENTDATE DATE
);     
-- 0 +/- SELECT COUNT(*) FROM PA.COMMENTARY;  
CREATE CACHED TABLE PA.ELEMENT(
    ID INT NOT NULL,
    LABEL TEXT,
    DESCRIPTION TEXT
);              
ALTER TABLE PA.ELEMENT ADD CONSTRAINT PA.CONSTRAINT_C PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PA.ELEMENT;     
CREATE CACHED TABLE PA.EQUATIONELEMENT(
    ID INT NOT NULL,
    ELE_ID INT
);             
-- 0 +/- SELECT COUNT(*) FROM PA.EQUATIONELEMENT;             
CREATE CACHED TABLE PA.RULE(
    ID INT NOT NULL,
    LABEL TEXT
);        
ALTER TABLE PA.RULE ADD CONSTRAINT PA.CONSTRAINT_2 PRIMARY KEY(ID);           
-- 4 +/- SELECT COUNT(*) FROM PA.RULE;        
INSERT INTO PA.RULE(ID, LABEL) VALUES
(1, 'Legislator'),
(2, 'Prescriber'),
(3, 'Proposer'),
(4, 'Evaluator');            
CREATE CACHED TABLE PA.RULEELEMENT(
    ID INT NOT NULL,
    ELE_ID INT,
    VAL TEXT
);  
-- 0 +/- SELECT COUNT(*) FROM PA.RULEELEMENT; 
CREATE CACHED TABLE PA.ELMTOPERATOR(
    ID INT NOT NULL
); 
-- 0 +/- SELECT COUNT(*) FROM PA.ELMTOPERATOR;
CREATE CACHED TABLE PA.ELMTVARIABLE(
    ID INT NOT NULL,
    VAL TEXT
);  
-- 0 +/- SELECT COUNT(*) FROM PA.ELMTVARIABLE;
CREATE CACHED TABLE PA.EQUATIONRULES(
    ID INT NOT NULL,
    RUL_ID INT
);               
-- 0 +/- SELECT COUNT(*) FROM PA.EQUATIONRULES;               
ALTER TABLE PA.EQUATION ADD CONSTRAINT PA.CONSTRAINT_5151 FOREIGN KEY(CREATEDBY) REFERENCES PA.USERS(ID) NOCHECK;             
ALTER TABLE PA.EQUATIONRULES ADD CONSTRAINT PA.CONSTRAINT_5196 FOREIGN KEY(RUL_ID) REFERENCES PA.RULE(ID) NOCHECK;            
ALTER TABLE PA.EQUATIONRULES ADD CONSTRAINT PA.CONSTRAINT_519 FOREIGN KEY(ID) REFERENCES PA.EQUATION(ID) NOCHECK;             
ALTER TABLE PA.COMMENTARY ADD CONSTRAINT PA.CONSTRAINT_528 FOREIGN KEY(EQU_ID) REFERENCES PA.EQUATION(ID) NOCHECK;            
ALTER TABLE PA.EQUATION ADD CONSTRAINT PA.CONSTRAINT_515 FOREIGN KEY(VALIDATEDBY) REFERENCES PA.EQUATION(ID) NOCHECK;         
ALTER TABLE PA.ELMTOPERATOR ADD CONSTRAINT PA.CONSTRAINT_78 FOREIGN KEY(ID) REFERENCES PA.ELEMENT(ID) NOCHECK;
ALTER TABLE PA.EQUATIONELEMENT ADD CONSTRAINT PA.CONSTRAINT_88 FOREIGN KEY(ELE_ID) REFERENCES PA.ELEMENT(ID) NOCHECK;         
ALTER TABLE PA.RULEELEMENT ADD CONSTRAINT PA.CONSTRAINT_99 FOREIGN KEY(ELE_ID) REFERENCES PA.ELEMENT(ID) NOCHECK;             
ALTER TABLE PA.AUTHORISATIONROLE ADD CONSTRAINT PA.CONSTRAINT_79 FOREIGN KEY(AUT_ID) REFERENCES PA.AUTHORISATION(ID) NOCHECK; 
ALTER TABLE PA.AUTHORISATIONROLE ADD CONSTRAINT PA.CONSTRAINT_797 FOREIGN KEY(ID) REFERENCES PA.ROLESTATUT(ID) NOCHECK;       
ALTER TABLE PA.EQUATIONELEMENT ADD CONSTRAINT PA.CONSTRAINT_8 FOREIGN KEY(ID) REFERENCES PA.EQUATION(ID) NOCHECK;             
ALTER TABLE PA.RULEELEMENT ADD CONSTRAINT PA.CONSTRAINT_9 FOREIGN KEY(ID) REFERENCES PA.RULE(ID) NOCHECK;     
ALTER TABLE PA.COMMENTARY ADD CONSTRAINT PA.CONSTRAINT_52 FOREIGN KEY(ID) REFERENCES PA.USERS(ID) NOCHECK;    
ALTER TABLE PA.USERROLE ADD CONSTRAINT PA.CONSTRAINT_1 FOREIGN KEY(ID) REFERENCES PA.USERS(ID) NOCHECK;       
ALTER TABLE PA.ELMTVARIABLE ADD CONSTRAINT PA.CONSTRAINT_4B FOREIGN KEY(ID) REFERENCES PA.ELEMENT(ID) NOCHECK;
ALTER TABLE PA.USERS ADD CONSTRAINT PA.CONSTRAINT_4D FOREIGN KEY(ID_PASSWORD) REFERENCES PA.PASSWORD(ID) NOCHECK;             
ALTER TABLE PA.USERROLE ADD CONSTRAINT PA.CONSTRAINT_1E FOREIGN KEY(ROL_ID) REFERENCES PA.ROLESTATUT(ID) NOCHECK;             
